32-function-for-accessing-the-users-current-language
numere-org/NumeRe pull request #100
Opened 2023-05-06 21:07 UTC by durveshps

### SUMMARY
Implements necessary changes for #[ISSUE-ID]

*Reviewers:* @numere-org/maintainers

### IMPLEMENTATION
* Implementation: (*Describe, what you've changed*) 
* Implementation test: (*Describe the type of test, which you performed, and if it was successful*)

### DOCUMENTATION
* [ ] ChangesLog updated
* [ ] Code changes commented
* **Documentation articles:**
    * [ ] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [ ] not needed
* **Language files:**
    * [ ] corresponding language files updated
    * [ ] not needed

----------------

### TESTS BY REVIEWERS
* [ ] Added to the automatic SW tests
* [ ] Tested manually

2023-05-22 07:13 UTC, numeredev requested changes
Please use `_lang` in the kernel component and `_guilang` in the GUI component.

2023-05-22 07:13 UTC, numeredev commented on kernel/core/strings/stringfunctions.hpp
> +extern Language _guilang;
```suggestion
extern Language _lang;

```
Works with both, but I'd like to have both instances separated.

2023-05-22 07:14 UTC, numeredev commented
Needs the addition of `getuilang()` at the other locations in code (about two).

2023-05-22 12:39 UTC, durveshps commented
A side question, I was trying to test this, but it threw error that getuilang function does not exist. Is it also becuase I used _guilang and not _lang?

2023-05-22 12:45 UTC, numeredev commented
> A side question, I was trying to test this, but it threw error that getuilang function does not exist. Is it also becuase I used _guilang and not _lang?

Nope, I think that's because the parser does not yet know, how to find the function. For testing, try to enter `getuilang() + ""`. For production, you've to search for occurences of `getversioninfo(` in code and add `getuilang(` to those conditions.

2023-06-23 18:02 UTC, numeredev reviewed
Changes accepted. Will be merged after tests have been implemented.

2023-06-23 18:05 UTC, numeredev commented
> Changes accepted. Will be merged after tests have been implemented.

@durveshps You're missing the entry in the ChangesLog. Please add that.

2023-06-26 15:06 UTC, MarkRamp commented
@numeredev I updated changes.tmp, I hope that is what you meant.

2023-06-26 15:23 UTC, merged