25 enable clear var in terminal
numere-org/NumeRe pull request #140
Opened 2023-09-06 09:39 UTC by durveshps

### SUMMARY
Implements necessary changes for #[ISSUE-ID]

*Reviewers:* @numere-org/maintainers

### IMPLEMENTATION
* Implementation: (*Describe, what you've changed*) 
* Implementation test: (*Describe the type of test, which you performed, and if it was successful*)

### DOCUMENTATION
* [ ] ChangesLog updated
* [ ] Code changes commented
* **Documentation articles:**
    * [ ] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [ ] not needed
* **Language files:**
    * [ ] corresponding language files updated
    * [ ] not needed

----------------

### TESTS BY REVIEWERS
* [ ] Added to the automatic SW tests
* [ ] Tested manually

2023-09-06 10:51 UTC, durveshps commented
Ich habe die Grund-Funktionalität umgesetzt.

2023-09-06 10:53 UTC, durveshps commented on kernel/core/strings/stringvarfactory.cpp
> +    /// \param sVar const string&
should be corrected

2023-09-06 10:53 UTC, durveshps commented on kernel/core/commandfunctions.hpp
> +                // if ( sLegacyVar[i] == iter->first || iter->first[0] == "~" || iter->first[0] == "_")
can be removed

2023-09-06 14:44 UTC, numeredev requested changes
Please check, whether those suggestions work. Feel free to ask questions 😉

2023-09-06 14:44 UTC, numeredev commented on kernel/core/strings/stringvarfactory.cpp
> +	    }
```suggestion
        if (!iter->first.starts_with("_~"))
	        m_mStringVars.erase(iter);
```

This is, what you probably meant.

2023-09-06 14:44 UTC, numeredev commented on kernel/core/strings/stringvarfactory.cpp
> +    /// \param sVar const string&
Yes please

2023-09-06 14:44 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +        static vector<string> sLegacyVar = {"t", "x", "y", "z", "ncols", "nlens", "nlines", "nrows", "ans"};
```suggestion
        static std::vector<std::string> dafaultVars = {"t", "x", "y", "z", "ncols", "nlens", "nlines", "nrows", "ans"};
```

2023-09-06 14:44 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +    else if (cmdParser.hasParam("var"))
```suggestion
    else if (cmdParser.hasParam("var") && NumeReKernel::getInstance()->getDebugger().getStackSize() == 0)
```
You want to ensure that this is only allowed within the terminal out of any procedures or flow control statements.

2023-09-14 14:09 UTC, MarkRamp commented
> Please check, whether those suggestions work. Feel free to ask questions 😉

I have made all of the changes, clear -memory will now also call -var, becuase memory word is superior to variable, I think its ready to be merged.

2023-09-14 14:51 UTC, numeredev requested changes
Some minor changes still open. There should also be an update to `data_and_fileops.nhlp` in both languages to explain the behavior of `clear -var`

2023-09-14 14:51 UTC, numeredev commented on kernel/core/strings/stringvarfactory.cpp
> +	}
```suggestion
	    if (!m_mStringVars.size())
            return;

	    for (auto iter = m_mStringVars.begin(); iter != m_mStringVars.end(); ++iter)
	    {
	        if (!iter->first.starts_with("_~"))
	            m_mStringVars.erase(iter);
	    }
```

2023-09-14 14:51 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +	// Clear also user-defined variables
```suggestion
	// Clear also user-defined variables if called from terminal
```

2023-09-14 14:51 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +	clear_variables();
```suggestion
	    clear_variables();
```

2023-09-14 14:51 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +    // check if user-defined variable is legacy variable and call is from terminal
Comment does not make any sense. It should be something like `remove variables, which are not default variables and no temporary variables`

2023-09-14 14:51 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +	    _parser.RemoveVar(iter->first);
```suggestion
	    bool isTemporaryVar = iter->first.starts_with("_~");
	    bool isDefaultVar = std::find(defaultVars.begin(), defaultVars.end(), iter->first) != defaultVars.end();
	    if (!isTemporaryVar && !isDefaultVar)
	        _parser.RemoveVar(iter->first);
```

2023-09-14 14:54 UTC, numeredev commented on kernel/core/strings/stringvarfactory.cpp
> +	}
Addendum: obviously this file contains a mixture of whitespaces and tabs for some reason. Do only apply indentation suggestions, if they are reasonable

2023-09-15 14:06 UTC, MarkRamp commented
Translation PR 
https://github.com/numere-org/Translation/pull/20

2023-09-15 17:26 UTC, numeredev commented on kernel/core/commandfunctions.hpp
>      else if (cmdParser.hasParam("memory"))
```suggestion
    else if (cmdParser.hasParam("memory") && NumeReKernel::getInstance()->getDebugger().getStackSize() == 0)
```

2023-09-15 17:27 UTC, numeredev commented on kernel/core/commandfunctions.hpp
> +	}
```suggestion
	clear_variables();
```

2023-09-15 17:45 UTC, merged