Implements necessary changes for #50
numere-org/NumeRe pull request #85
Opened 2023-04-17 14:22 UTC by Umashankar5995

### SUMMARY

Implements necessary changes for #50 

*Reviewers:* @numere-org/maintainers

### IMPLEMENTATION
* Implementation: (*Describe, what you've changed*) 
* Implementation test: (*Describe the type of test, which you performed, and if it was successful*)

### DOCUMENTATION
* [ ] ChangesLog updated
* [ ] Code changes commented
* **Documentation articles:**
    * [ ] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [ ] not needed
* **Language files:**
    * [ ] corresponding language files updated
    * [ ] not needed

----------------

### TESTS BY REVIEWERS
* [ ] Added to the automatic SW tests
* [ ] Tested manually

2023-04-24 16:11 UTC, numeredev commented on gui/terminal/terminal.cpp
> +		if (_kernel.getAutosaveInterval() > 0 && (time(0)-_kernel.getLastSavedTime()>=_kernel.getAutosaveInterval()))
```suggestion
		if (_kernel.getAutosaveInterval() > 0 && (time(0) - _kernel.getLastSavedTime() >= _kernel.getAutosaveInterval()))

```
We prefer, if there's whitespace around the operators

2023-04-24 16:12 UTC, numeredev requested changes
Please correct the styling and add the missing changes log as well.

2023-04-26 14:33 UTC, Umashankar5995 commented
if (_kernel.getAutosaveInterval() > 0 && (time(0) - _kernel.getLastSavedTime() >= _kernel.getAutosaveInterval()))

2023-04-26 14:52 UTC, numeredev commented on Debug/Profiling/NumeRe.res
Please remove this file. It is auto-created and binary

2023-04-28 15:12 UTC, numeredev approved these changes
Changes accepted. Will be merged

2023-04-28 15:12 UTC, merged